// Generated by CoffeeScript 2.7.0
(function() {
  var CreateProject, Template;

  ({Template} = require('./Template'));

  ({CreateProject} = require('./CreateProject'));

  exports.CreateFileTree = async function(variables) {
    var name, project, template;
    ({name, template} = variables);
    template = Template(template);
    if (template.exists) {
      project = (await CreateProject({name, template}));
      return project.dir;
    } else {
      console.error(template.error);
      return process.exit(1);
    }
  };

}).call(this);
