// Generated by CoffeeScript 2.7.0
(function() {
  var ProjectFile;

  ({ProjectFile} = require('./ProjectFile'));

  require('./helpers');

  exports.Project = bow({
    init: {
      name: null,
      template: null,
      dir: null
    },
    methods: {
      create_new_file_from: async function(template_file) {
        var filename, output, project, project_file, text;
        project_file = ProjectFile(template_file.transpose_to(this.dir));
        if (template_file.is_evaluable()) {
          project = this;
          output = (await template_file.output_for({project}));
          if (text = output.text) {
            if (filename = output.filename) {
              project_file.change_filename_to(filename);
            }
          } else {
            text = output;
          }
          await project_file.write(text);
          if (output.executable) {
            await sh(`chmod +x ${project_file.path}`);
          }
        } else {
          await project_file.copy(template_file.path);
        }
        return project_file.path;
      }
    }
  });

}).call(this);
