// Generated by CoffeeScript 2.7.0
(function() {
  var init, methods, setup;

  require('./helpers');

  init = require('./Project/init');

  setup = require('./Project/setup');

  methods = require('./Project/methods');

  exports.Project = bow({init, setup, methods});

}).call(this);
