// Generated by CoffeeScript 2.7.0
(function() {
  var compile, read;

  ({compile} = require('coffeescript'));

  ({read} = IO.sync);

  require('./String');

  exports.TemplateFile = bow({
    init: function({ext, path, template_path}) {
      this.ext = ext;
      this.path = path;
      this.template_path = template_path;
      return this.relative_path = path.delete_prefix(`${template_path}/`);
    },
    methods: {
      transpose_to: function(dir) {
        if (this.path.endsWith(this.ext)) {
          return `${dir}/${this.relative_path}`.delete_suffix(this.ext);
        } else {
          return `${dir}/${this.relative_path}`;
        }
      },
      endsWith: function(suffix) {
        return this.path.endsWith(suffix);
      },
      read: function() {
        return read(this.path);
      },
      is_evaluable: function() {
        return this.path.endsWith(this.ext);
      },
      output_for: async function({project}) {
        var code;
        code = (await this.read());
        switch (this.ext) {
          case '.js':
            return eval(code);
          case '.coffee':
            return eval(compile(code, {
              bare: true
            }));
        }
      }
    }
  });

}).call(this);
