// Generated by CoffeeScript 2.7.0
(function() {
  var TemplateFile, exists;

  ({exists} = IO.sync);

  ({TemplateFile} = require('./TemplateFile'));

  exports.Template = bow({
    init: function(input) {
      var base, ext, file, files, metafile, path;
      path = `${COFFEELIB.path}/node_modules/coffeelib.templates/lib/${input}`;
      if (exists(path)) {
        this.exists = true;
        ext = '.js';
      } else if (exists(input)) {
        this.exists = true;
        ext = '.coffee';
        path = input;
      } else {
        this.error = `No template directory was found at ${path}`;
      }
      if (this.exists) {
        metafile = `${path}/template.coffee`;
        if (exists(metafile)) {
          this.metafile = metafile;
          this.type = 'complex';
          base = `${path}/base`;
        } else {
          this.type = 'simple';
          base = path;
        }
        files = glob.sync(`${base}/**/*`, {
          nodir: true
        });
        return this.files = (function() {
          var i, len, results;
          results = [];
          for (i = 0, len = files.length; i < len; i++) {
            file = files[i];
            results.push(TemplateFile({
              ext: ext,
              path: file,
              template_path: base
            }));
          }
          return results;
        })();
      }
    }
  });

}).call(this);
