// Generated by CoffeeScript 2.7.0
(function() {
  var Jasmine, default_config, exists, read;

  ({read, exists} = IO.sync);

  Jasmine = require('jasmine');

  default_config = {
    spec_dir: 'spec',
    spec_files: ['**/*.spec.coffee'],
    helpers: ['helpers/**/*.coffee'],
    stopSpecOnExpectationFailure: false,
    jsLoader: 'require',
    random: true
  };

  exports.CreateJasmine = function() {
    var config, custom_config, custom_config_path, jasmine;
    jasmine = new Jasmine();
    custom_config_path = 'spec/support/jasmine.json';
    if (exists(custom_config_path)) {
      custom_config = JSON.parse(read(custom_config_path));
      config = {...default_config, ...custom_config};
    } else {
      config = default_config;
    }
    jasmine.loadConfig(config);
    jasmine.configureDefaultReporter({
      showColors: true
    });
    jasmine.exitOnCompletion = false;
    return jasmine;
  };

}).call(this);
