// Generated by CoffeeScript 2.7.0
(function() {
  var compile, read;

  ({compile} = require('coffeescript'));

  ({read} = IO.sync);

  module.exports = async function() {
    var code, metafile, metafile_output, project;
    switch (this.template.type) {
      case 'simple':
        await this.create_files();
        break;
      case 'complex':
        ({metafile} = this.template);
        code = (await read(metafile));
        project = this;
        metafile_output = eval(compile(code, {
          bare: true
        }));
        if (typeof metafile_output === 'function') {
          metafile_output.call(this);
        }
        await this.create_files();
    }
    return this;
  };

}).call(this);
